<?php

namespace Database\Seeders;

use App\Models\UserQuestion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class UserQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        UserQuestion::truncate();
        Schema::enableForeignKeyConstraints();

        $user_question = array(
            array('user_acl_profession_id' => '1', 'employer_question' => 'Question one for Employer ?', 'freelancer_question' => 'Question one for locum ?', 'type' => '2', 'values' => 'a:8:{i:0;s:6:"opton1";i:1;s:7:"option2";i:2;s:7:"option3";i:3;s:7:"option4";i:4;s:7:"option5";i:5;s:7:"option6";i:6;s:7:"option7";i:7;s:3:"op8";}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'How many years does the Optometrist need to be qualified?', 'freelancer_question' => 'How many years have you been qualified? ', 'type' => '5', 'values' => 'a:7:{i:0;s:3:"0-1";i:1;s:3:"2-5";i:2;s:4:"6-10";i:3;s:5:"11-15";i:4;s:5:"16-20";i:5;s:5:"21-25";i:6;s:5:"26-50";}', 'sort_order' => '1', 'is_required' => '1', 'range_type_unit' => 'Year', 'range_type_condition' => '4'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'Testing time offered for a standard eye examination', 'freelancer_question' => 'What is your standard testing time for an eye examination?', 'type' => '5', 'values' => 'a:7:{i:0;s:5:"10-15";i:1;s:5:"16-20";i:2;s:5:"21-25";i:3;s:5:"26-30";i:4;s:5:"31-35";i:5;s:5:"36-40";i:6;s:5:"41-45";}', 'sort_order' => '3', 'is_required' => '1', 'range_type_unit' => 'Minutes', 'range_type_condition' => '4'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'Testing time offered for CL fit or standard contact lens aftercare', 'freelancer_question' => 'What is your testing time for a standard CL fit or aftercare appointment', 'type' => '5', 'values' => 'a:4:{i:0;s:5:"10-15";i:1;s:5:"16-20";i:2;s:5:"21-25";i:3;s:5:"26-30";}', 'sort_order' => '4', 'is_required' => '1', 'range_type_unit' => 'Minutes', 'range_type_condition' => '4'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'Optometrist required to supervise a pre-reg?', 'freelancer_question' => 'Are you ok to supervise a pre-reg?', 'type' => '6', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '11', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'Does the pharmacist need to have have experience in any of the following pharmacies', 'freelancer_question' => 'Do you have experience in any of the following pharmacies?', 'type' => '3', 'values' => 'a:6:{i:0;s:10:"Low volume";i:1;s:11:"High volume";i:2;s:15:"Patient Centric";i:3;s:14:"Service driven";i:4;s:11:"Independent";i:5;s:8:"Multiple";}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'Does the pharmacist need to have experience with any of the following pharmacy systems', 'freelancer_question' => 'Do you have experience with any of the following pharmacy systems', 'type' => '3', 'values' => 'a:9:{i:0;s:3:"MUR";i:1;s:3:"NMS";i:2;s:15:"Needle Exchange";i:3;s:20:"Supervised Methadone";i:4;s:16:"Flu Vaccinations";i:5;s:20:"Minor Ailment Scheme";i:6;s:9:"BP checks";i:7;s:18:"Blood sugar checks";i:8;s:18:"Cholesterol checks";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'Does the pharmacist need to be providing or have provided any services under PGDâ€™s', 'freelancer_question' => 'Do you provide or have provided any services under PGDâ€™s', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'Does the pharmacist need to be omfortable checking Dossette boxes', 'freelancer_question' => 'Are you comfortable checking Dossette boxes', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'Does the pharmacist need to be upto date with CPD', 'freelancer_question' => 'Are you upto date with CPD', 'type' => '3', 'values' => 'a:3:{i:0;s:3:"Yes";i:1;s:2:"No";i:2;s:3:"N/A";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'CPD: If yes when should be their last entry', 'freelancer_question' => 'CPD: If so when was your last entry', 'type' => '2', 'values' => 'a:8:{i:0;s:15:"1 Month or less";i:1;s:8:"2 Month ";i:2;s:7:"3 Month";i:3;s:7:"4 Month";i:4;s:7:"5 Month";i:5;s:7:"6 Month";i:6;s:7:"1 year ";i:7;s:11:"1 year plus";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'Does the pharmacist need to be familiar with the Nomad systems available', 'freelancer_question' => 'Are you familiar with the Nomad systems available', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'How long does the pharmacist need to be qualified for', 'freelancer_question' => 'How long have you been qualified', 'type' => '2', 'values' => 'a:6:{i:0;s:6:"1 year";i:1;s:9:"2-5 years";i:2;s:10:"6-10 years";i:3;s:11:"11-15 years";i:4;s:11:"16-20 years";i:5;s:13:"20 years plus";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'What is your GPC number', 'type' => '1', 'values' => 'a:1:{i:0;s:0:"";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'What is your NPA number', 'type' => '1', 'values' => 'a:1:{i:0;s:0:"";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'If you are not insured with NPA, who is your insurer and when is your renewal date?', 'type' => '1', 'values' => 'a:1:{i:0;s:0:"";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'What University did you graduate from?', 'type' => '2', 'values' => 'a:2:{i:0;s:20:"Cambridge University";i:1;s:21:"Manchester University";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => 'When was the last time you require the pharmacist to have worked for your store?', 'freelancer_question' => 'Which of the following stores have you worked at and when was the last time you worked there?', 'type' => '3', 'values' => 'a:3:{i:0;s:15:"Lloyds Pharmacy";i:1;s:16:"Redwell Pharmacy";i:2;s:7:"DrFelix";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'How far are you willling to travel? Please unselect stores you are not willing to travel to', 'type' => '2', 'values' => 'a:11:{i:0;s:7:"5 Miles";i:1;s:8:"10 Miles";i:2;s:8:"15 Miles";i:3;s:8:"20 Miles";i:4;s:8:"25 Miles";i:5;s:8:"30 Miles";i:6;s:8:"35 Miles";i:7;s:8:"40 Miles";i:8;s:8:"45 Miles";i:9;s:8:"50 Miles";i:10;s:13:"Over 50 Miles";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'How would you like to recieve notification', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"SMS";i:1;s:5:"Email";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'What languages can you speak?', 'type' => '3', 'values' => 'a:2:{i:0;s:7:"English";i:1;s:5:"Hindi";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '4', 'employer_question' => '', 'freelancer_question' => 'How do you travel to work?', 'type' => '3', 'values' => 'a:5:{i:0;s:3:"Car";i:1;s:9:"Bus/Train";i:2;s:5:"Cycle";i:3;s:4:"Walk";i:4;s:5:"Other";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'Specific languages the locum should know', 'freelancer_question' => 'Which of the following languages can you speak?', 'type' => '3', 'values' => 'a:11:{i:0;s:7:"English";i:1;s:6:"Arabic";i:2;s:7:"Bengali";i:3;s:7:"Chinese";i:4;s:8:"Gujarati";i:5;s:7:"Punjabi";i:6;s:6:"Somali";i:7;s:5:"Tamil";i:8;s:4:"Urdu";i:9;s:7:"Italian";i:10;s:6:"Polish";}', 'sort_order' => '10', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'What area of specialism, if any, do you require the Optician to have?', 'freelancer_question' => 'Which of the following areas have you specialised in?', 'type' => '3', 'values' => 'a:10:{i:0;s:14:"Basic Eye Test";i:1;s:8:"Glaucoma";i:2;s:10:"Low Vision";i:3;s:20:"Primary Subscription";i:4;s:5:"PEARS";i:5;s:13:"CL specialist";i:6;s:17:"Cataract referral";i:7;s:14:"Medical Retina";i:8;s:3:"OCT";i:9;s:4:"MECS";}', 'sort_order' => '9', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '1', 'employer_question' => '', 'freelancer_question' => '', 'type' => '4', 'values' => 'a:4:{i:0;s:1:"1";i:1;s:1:"2";i:2;s:1:"3";i:3;s:1:"4";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => 'Years', 'range_type_condition' => '5'),
            array('user_acl_profession_id' => '1', 'employer_question' => 'Yes-No qus TEST ?', 'freelancer_question' => 'Yes-No qus TEST?', 'type' => '6', 'values' => 'a:0:{}', 'sort_order' => '1', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => 'How many years does the optician need to be qualified?', 'freelancer_question' => 'How many years have you been qualified?', 'type' => '5', 'values' => 'a:7:{i:0;s:3:"0-1";i:1;s:3:"1-2";i:2;s:3:"2-3";i:3;s:3:"3-5";i:4;s:4:"5-10";i:5;s:5:"10-20";i:6;s:5:"20-50";}', 'sort_order' => '1', 'is_required' => '1', 'range_type_unit' => 'Years', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => 'Testing time offered for a standard eye examination?', 'freelancer_question' => 'What is your standard testing time?', 'type' => '5', 'values' => 'a:4:{i:0;s:5:"20-30";i:1;s:5:"30-40";i:2;s:5:"40-50";i:3;s:5:"50-60";}', 'sort_order' => '2', 'is_required' => '1', 'range_type_unit' => 'Minutes', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => 'Does the locum need to be a car owner?', 'freelancer_question' => 'Are you a car owner?', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '3', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => 'Specific languages the locum should know?', 'freelancer_question' => 'What languages can you speak? ', 'type' => '3', 'values' => 'a:11:{i:0;s:7:"English";i:1;s:6:"Arabic";i:2;s:7:"Bengali";i:3;s:7:"Chinese";i:4;s:7:"Gujrati";i:5;s:7:"Punjabi";i:6;s:6:"Somali";i:7;s:5:"Tamil";i:8;s:4:"Urdu";i:9;s:7:"Italian";i:10;s:6:"Polish";}', 'sort_order' => '4', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => '', 'freelancer_question' => 'How would you like to recieve notification?', 'type' => '3', 'values' => 'a:2:{i:0;s:5:"Email";i:1;s:3:"SMS";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => 'What area of specialism, if any, do you require the Optician to have?', 'freelancer_question' => 'Do you have any areas of specialism?', 'type' => '3', 'values' => 'a:8:{i:0;s:14:"Basic Eye Test";i:1;s:8:"Glaucoma";i:2;s:10:"Low Vision";i:3;s:20:"Primary Subscription";i:4;s:5:"PEARS";i:5;s:13:"CL Specialist";i:6;s:17:"Cataract Referral";i:7;s:14:"Medical Retina";}', 'sort_order' => '5', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => '', 'freelancer_question' => 'What is your GOC NO?', 'type' => '1', 'values' => 'a:0:{}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '5', 'employer_question' => '', 'freelancer_question' => 'What is your AOP membership number?', 'type' => '1', 'values' => 'a:0:{}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '7', 'employer_question' => '', 'freelancer_question' => 'testing', 'type' => '6', 'values' => 'a:0:{}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '7', 'employer_question' => 'testing second quation', 'freelancer_question' => '', 'type' => '1', 'values' => 'a:0:{}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '8', 'employer_question' => 'How many years does the Optometrist need to be qualified?', 'freelancer_question' => 'How many years have you been qualified? ', 'type' => '5', 'values' => 'a:9:{i:0;s:1:"5";i:1;s:2:"10";i:2;s:3:"0-1";i:3;s:3:"2-5";i:4;s:4:"6-10";i:5;s:5:"11-15";i:6;s:5:"16-20";i:7;s:5:"21-25";i:8;s:5:"26-30";}', 'sort_order' => '1', 'is_required' => '1', 'range_type_unit' => 'Year', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '9', 'employer_question' => 'How long should the Audiologist have been qualified for?', 'freelancer_question' => 'How long have you been qualified?', 'type' => '2', 'values' => 'a:3:{i:0;s:8:"0-1 year";i:1;s:8:"1-2 year";i:2;s:8:"3-5 year";}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '9', 'employer_question' => 'What is the testing time required?', 'freelancer_question' => 'What is your testing time?', 'type' => '2', 'values' => 'a:4:{i:0;s:5:"20-30";i:1;s:5:"31-40";i:2;s:5:"41-50";i:3;s:5:"51-60";}', 'sort_order' => '0', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '9', 'employer_question' => 'What is the required aftercare timing?', 'freelancer_question' => 'What is your aftercare testing time?', 'type' => '3', 'values' => 'a:3:{i:0;s:5:"10-20";i:1;s:5:"21-30";i:2;s:5:"31-40";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '9', 'employer_question' => 'What langues do you need?', 'freelancer_question' => 'What languages can you speak?', 'type' => '3', 'values' => 'a:5:{i:0;s:7:"English";i:1;s:6:"Arabic";i:2;s:7:"Bengali";i:3;s:7:"Gujrati";i:4;s:7:"Chinese";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '9', 'employer_question' => 'Do you need supervision?', 'freelancer_question' => 'Can you supervise?', 'type' => '6', 'values' => 'a:0:{}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'Equipment list', 'freelancer_question' => 'Equipment list', 'type' => '3', 'values' => 'a:58:{i:0;s:13:"Autorefractor";i:1;s:10:"Cross Cyls";i:2;s:8:"Flippers";i:3;s:21:"Digital fundus camera";i:4;s:29:"Focimeter - Manual, automatic";i:5;s:21:"Focimeter - Automatic";i:6;s:26:"Keratometer - One position";i:7;s:26:"Keratometer - Two position";i:8;s:3:"OCT";i:9;s:23:"Ophthalmoscope - Keeler";i:10;s:28:"Ophthalmoscope - Welsh Allen";i:11;s:22:"Ophthalmoscope - Heine";i:12;s:26:"Ophthalmoscope - Pan optic";i:13;s:20:"Retinoscope - Keeler";i:14;s:26:"Retinoscope - Welsch Allen";i:15;s:19:"Retinoscope - Heine";i:16;s:9:"Slit lamp";i:17;s:17:"Slit lamp - Nikon";i:18;s:18:"Slit lamp - Keeler";i:19;s:18:"Slit lamp - Topcon";i:20;s:23:"Slit lamp - Haag Streit";i:21;s:58:"Test charts - Contrast sentivity test chart (Pelli-Robson)";i:22;s:20:"Test Charts - Logmar";i:23;s:21:"Test Charts - Snellen";i:24;s:29:"Test Charts - Test chart 2000";i:25;s:26:"Test Charts - Computerised";i:26;s:19:"Tonometer - Goldman";i:27;s:19:"Tonometer - Perkins";i:28;s:19:"Tonometer - Pulsair";i:29;s:29:"Tonometer - Nidek non contact";i:30;s:17:"Tonometer - icare";i:31;s:11:"Trial Frame";i:32;s:15:"Trial lens case";i:33;s:19:"Visual fields - FDT";i:34;s:39:"Visual fields - Henson (various models)";i:35;s:41:"Visual fields - Humphrey (various models)";i:36;s:25:"Visual fields - Estermann";i:37;s:14:"Refractor head";i:38;s:26:"Refractor head - Phoropter";i:39;s:36:"Volk Lens - 90D, 20D, Superfield 78D";i:40;s:22:"Accommodative flippers";i:41;s:25:"Stereoscopic tests - Lang";i:42;s:28:"Stereoscopic tests - Cardiff";i:43;s:31:"Stereoscopic tests - Titmus Fly";i:44;s:10:"Prism Bars";i:45;s:26:"RAF rule for accomodoation";i:46;s:11:"Maddox Wing";i:47;s:16:"Near Mallet Unit";i:48;s:20:"Distance Mallet Unit";i:49;s:24:"Colour vision - Ishihara";i:50;s:20:"Colour vision - City";i:51;s:12:"Amsler chart";i:52;s:12:"Pupillometer";i:53;s:32:"Dispensing equipment - City Rule";i:54;s:38:"Dispensing equipment - Abdo frame rule";i:55;s:35:"Dispensing equipment - Lens Measure";i:56;s:11:"Burton lamp";i:57;s:11:"Topographer";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '8', 'employer_question' => 'Specific languages the locum should know', 'freelancer_question' => 'Which of the following languages can you speak?', 'type' => '3', 'values' => 'a:11:{i:0;s:7:"English";i:1;s:6:"Arabic";i:2;s:7:"Bengali";i:3;s:7:"Chinese";i:4;s:8:"Gujarati";i:5;s:7:"Punjabi";i:6;s:6:"Somali";i:7;s:5:"Tamil";i:8;s:4:"Urdu";i:9;s:8:"Italian ";i:10;s:6:"Polish";}', 'sort_order' => '10', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '8', 'employer_question' => 'Do you require the DO to supervise a pre-reg?', 'freelancer_question' => 'Are you ok to supervise a pre-reg?', 'type' => '6', 'values' => 'a:0:{}', 'sort_order' => '11', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '3', 'employer_question' => 'Which of the following IT systems are does the locum need to be comfortable with', 'freelancer_question' => 'Which of the following IT systems are you comfortable with', 'type' => '3', 'values' => 'a:6:{i:0;s:14:"Basic IT usage";i:1;s:7:"Acuitus";i:2;s:8:"Socrates";i:3;s:13:"Tommy (Tesco)";i:4;s:5:"Ocuco";i:5;s:5:"Optix";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '10', 'employer_question' => 'Which of the following IT systems are does the locum need to be comfortable with', 'freelancer_question' => 'Which of the following IT systems are you comfortable with', 'type' => '3', 'values' => 'a:6:{i:0;s:14:"Basic IT usage";i:1;s:7:"Acuitus";i:2;s:8:"Socrates";i:3;s:13:"Tommy (Tesco)";i:4;s:5:"Ocuco";i:5;s:5:"Optix";}', 'sort_order' => '3', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '9', 'employer_question' => 'How many years does the Optometrist need to be qualified?', 'freelancer_question' => 'How many years have you been qualified? ', 'type' => '5', 'values' => 'a:7:{i:0;s:3:"0-1";i:1;s:3:"2-5";i:2;s:4:"6-10";i:3;s:5:"11-15";i:4;s:5:"16-20";i:5;s:5:"21-25";i:6;s:5:"26-50";}', 'sort_order' => '0', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '10', 'employer_question' => 'Specific languages the locum should know', 'freelancer_question' => 'Which of the following languages can you speak?', 'type' => '3', 'values' => 'a:11:{i:0;s:7:"English";i:1;s:6:"Arabic";i:2;s:7:"Bengali";i:3;s:7:"Chinese";i:4;s:8:"Gujarati";i:5;s:7:"Punjabi";i:6;s:6:"Somali";i:7;s:5:"Tamil";i:8;s:4:"Urdu";i:9;s:7:"Italian";i:10;s:6:"Polish";}', 'sort_order' => '2', 'is_required' => '1', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '10', 'employer_question' => 'Is the DO required to supervise a pre-reg?', 'freelancer_question' => 'Are you ok to supervise a pre-reg?', 'type' => '6', 'values' => 'a:0:{}', 'sort_order' => '4', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '10', 'employer_question' => 'Do you require a CLO', 'freelancer_question' => 'Please confirm whether you are also a CLO', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '1', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0'),
            array('user_acl_profession_id' => '10', 'employer_question' => 'Does the DO need to be able to glaze?', 'freelancer_question' => 'Can you glaze in the lab', 'type' => '2', 'values' => 'a:2:{i:0;s:3:"Yes";i:1;s:2:"No";}', 'sort_order' => '5', 'is_required' => '0', 'range_type_unit' => '', 'range_type_condition' => '0')
        );

        $db_user_question = array();

        foreach ($user_question as $question) {
            $db_question = array();
            $db_question["user_acl_profession_id"] = $question["user_acl_profession_id"];
            $db_question["employer_question"] = $question["employer_question"] ? $question["employer_question"] : null;
            $db_question["freelancer_question"] = $question["freelancer_question"] ? $question["freelancer_question"] : null;
            $db_question["type"] = $question["type"];
            $db_question["values"] = unserialize($question["values"]) ? json_encode(unserialize($question["values"])) : null;
            $db_question["sort_order"] = $question["sort_order"] ? $question["sort_order"] : 0;
            $db_question["is_required"] = $question["is_required"] == "1" ? true : false;
            $db_question["range_type_unit"] = $question["range_type_unit"] ? $question["range_type_unit"] : null;
            $db_question["range_type_condition"] = $question["range_type_condition"] ? $question["range_type_condition"] : null;
            $db_question["created_at"] = now();
            $db_question["updated_at"] = now();

            if (in_array($db_question["user_acl_profession_id"], [1, 3, 4, 8, 910])) {
                $db_user_question[] = $db_question;
            }
        }

        UserQuestion::insert($db_user_question);
    }
}