<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserAclDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user_acl = array(
            array('id' => '177', 'user_acl_permission_id' => '1', 'user_acl_role_id' => '5'),
            array('id' => '178', 'user_acl_permission_id' => '3', 'user_acl_role_id' => '5'),
            array('id' => '179', 'user_acl_permission_id' => '4', 'user_acl_role_id' => '5'),
            array('id' => '191', 'user_acl_permission_id' => '68', 'user_acl_role_id' => '8'),
            array('id' => '192', 'user_acl_permission_id' => '69', 'user_acl_role_id' => '8'),
            array('id' => '193', 'user_acl_permission_id' => '70', 'user_acl_role_id' => '8'),
            array('id' => '194', 'user_acl_permission_id' => '73', 'user_acl_role_id' => '8'),
            array('id' => '195', 'user_acl_permission_id' => '56', 'user_acl_role_id' => '8'),
            array('id' => '196', 'user_acl_permission_id' => '57', 'user_acl_role_id' => '8'),
            array('id' => '197', 'user_acl_permission_id' => '71', 'user_acl_role_id' => '8'),
            array('id' => '198', 'user_acl_permission_id' => '72', 'user_acl_role_id' => '8'),
            array('id' => '241', 'user_acl_permission_id' => '55', 'user_acl_role_id' => '10'),
            array('id' => '253', 'user_acl_permission_id' => '44', 'user_acl_role_id' => '9'),
            array('id' => '254', 'user_acl_permission_id' => '45', 'user_acl_role_id' => '9'),
            array('id' => '255', 'user_acl_permission_id' => '46', 'user_acl_role_id' => '9'),
            array('id' => '256', 'user_acl_permission_id' => '47', 'user_acl_role_id' => '9'),
            array('id' => '257', 'user_acl_permission_id' => '48', 'user_acl_role_id' => '9'),
            array('id' => '258', 'user_acl_permission_id' => '49', 'user_acl_role_id' => '9'),
            array('id' => '259', 'user_acl_permission_id' => '50', 'user_acl_role_id' => '9'),
            array('id' => '260', 'user_acl_permission_id' => '51', 'user_acl_role_id' => '9'),
            array('id' => '261', 'user_acl_permission_id' => '52', 'user_acl_role_id' => '9'),
            array('id' => '262', 'user_acl_permission_id' => '53', 'user_acl_role_id' => '9'),
            array('id' => '263', 'user_acl_permission_id' => '54', 'user_acl_role_id' => '9'),
            array('id' => '264', 'user_acl_permission_id' => '58', 'user_acl_role_id' => '9'),
            array('id' => '265', 'user_acl_permission_id' => '74', 'user_acl_role_id' => '11'),
            array('id' => '266', 'user_acl_permission_id' => '75', 'user_acl_role_id' => '11'),
            array('id' => '267', 'user_acl_permission_id' => '74', 'user_acl_role_id' => '12'),
            array('id' => '268', 'user_acl_permission_id' => '76', 'user_acl_role_id' => '12'),
            array('id' => '269', 'user_acl_permission_id' => '74', 'user_acl_role_id' => '13'),
            array('id' => '270', 'user_acl_permission_id' => '77', 'user_acl_role_id' => '13'),
            array('id' => '317', 'user_acl_permission_id' => '6', 'user_acl_role_id' => '14'),
            array('id' => '318', 'user_acl_permission_id' => '8', 'user_acl_role_id' => '14'),
            array('id' => '319', 'user_acl_permission_id' => '1', 'user_acl_role_id' => '4'),
            array('id' => '320', 'user_acl_permission_id' => '2', 'user_acl_role_id' => '4'),
            array('id' => '321', 'user_acl_permission_id' => '3', 'user_acl_role_id' => '4'),
            array('id' => '322', 'user_acl_permission_id' => '4', 'user_acl_role_id' => '4'),
            array('id' => '323', 'user_acl_permission_id' => '5', 'user_acl_role_id' => '4'),
            array('id' => '324', 'user_acl_permission_id' => '6', 'user_acl_role_id' => '4'),
            array('id' => '325', 'user_acl_permission_id' => '7', 'user_acl_role_id' => '4'),
            array('id' => '326', 'user_acl_permission_id' => '8', 'user_acl_role_id' => '4'),
            array('id' => '327', 'user_acl_permission_id' => '41', 'user_acl_role_id' => '4'),
            array('id' => '328', 'user_acl_permission_id' => '42', 'user_acl_role_id' => '4'),
            array('id' => '329', 'user_acl_permission_id' => '43', 'user_acl_role_id' => '4'),
            array('id' => '330', 'user_acl_permission_id' => '68', 'user_acl_role_id' => '4'),
            array('id' => '331', 'user_acl_permission_id' => '69', 'user_acl_role_id' => '4'),
            array('id' => '332', 'user_acl_permission_id' => '70', 'user_acl_role_id' => '4'),
            array('id' => '333', 'user_acl_permission_id' => '73', 'user_acl_role_id' => '4'),
            array('id' => '334', 'user_acl_permission_id' => '44', 'user_acl_role_id' => '4'),
            array('id' => '335', 'user_acl_permission_id' => '45', 'user_acl_role_id' => '4'),
            array('id' => '336', 'user_acl_permission_id' => '46', 'user_acl_role_id' => '4'),
            array('id' => '337', 'user_acl_permission_id' => '47', 'user_acl_role_id' => '4'),
            array('id' => '338', 'user_acl_permission_id' => '48', 'user_acl_role_id' => '4'),
            array('id' => '339', 'user_acl_permission_id' => '49', 'user_acl_role_id' => '4'),
            array('id' => '340', 'user_acl_permission_id' => '50', 'user_acl_role_id' => '4'),
            array('id' => '341', 'user_acl_permission_id' => '51', 'user_acl_role_id' => '4'),
            array('id' => '342', 'user_acl_permission_id' => '52', 'user_acl_role_id' => '4'),
            array('id' => '343', 'user_acl_permission_id' => '53', 'user_acl_role_id' => '4'),
            array('id' => '344', 'user_acl_permission_id' => '54', 'user_acl_role_id' => '4'),
            array('id' => '345', 'user_acl_permission_id' => '58', 'user_acl_role_id' => '4'),
            array('id' => '346', 'user_acl_permission_id' => '56', 'user_acl_role_id' => '4'),
            array('id' => '347', 'user_acl_permission_id' => '57', 'user_acl_role_id' => '4'),
            array('id' => '348', 'user_acl_permission_id' => '71', 'user_acl_role_id' => '4'),
            array('id' => '349', 'user_acl_permission_id' => '72', 'user_acl_role_id' => '4'),
            array('id' => '350', 'user_acl_permission_id' => '59', 'user_acl_role_id' => '4'),
            array('id' => '351', 'user_acl_permission_id' => '60', 'user_acl_role_id' => '4'),
            array('id' => '352', 'user_acl_permission_id' => '61', 'user_acl_role_id' => '4'),
            array('id' => '353', 'user_acl_permission_id' => '62', 'user_acl_role_id' => '4'),
            array('id' => '354', 'user_acl_permission_id' => '63', 'user_acl_role_id' => '4'),
            array('id' => '355', 'user_acl_permission_id' => '64', 'user_acl_role_id' => '4'),
            array('id' => '356', 'user_acl_permission_id' => '65', 'user_acl_role_id' => '4'),
            array('id' => '357', 'user_acl_permission_id' => '66', 'user_acl_role_id' => '4'),
            array('id' => '358', 'user_acl_permission_id' => '67', 'user_acl_role_id' => '4'),
            array('id' => '359', 'user_acl_permission_id' => '74', 'user_acl_role_id' => '4'),
            array('id' => '360', 'user_acl_permission_id' => '75', 'user_acl_role_id' => '4'),
            array('id' => '361', 'user_acl_permission_id' => '76', 'user_acl_role_id' => '4'),
            array('id' => '362', 'user_acl_permission_id' => '77', 'user_acl_role_id' => '4'),
            array('id' => '454', 'user_acl_permission_id' => '41', 'user_acl_role_id' => '6'),
            array('id' => '455', 'user_acl_permission_id' => '42', 'user_acl_role_id' => '6'),
            array('id' => '456', 'user_acl_permission_id' => '43', 'user_acl_role_id' => '6'),
            array('id' => '457', 'user_acl_permission_id' => '13', 'user_acl_role_id' => '2'),
            array('id' => '458', 'user_acl_permission_id' => '14', 'user_acl_role_id' => '2'),
            array('id' => '459', 'user_acl_permission_id' => '15', 'user_acl_role_id' => '2'),
            array('id' => '751', 'user_acl_permission_id' => '1', 'user_acl_role_id' => '15'),
            array('id' => '752', 'user_acl_permission_id' => '5', 'user_acl_role_id' => '15'),
            array('id' => '753', 'user_acl_permission_id' => '6', 'user_acl_role_id' => '15'),
            array('id' => '754', 'user_acl_permission_id' => '7', 'user_acl_role_id' => '15'),
            array('id' => '755', 'user_acl_permission_id' => '8', 'user_acl_role_id' => '15'),
            array('id' => '756', 'user_acl_permission_id' => '55', 'user_acl_role_id' => '15'),
            array('id' => '757', 'user_acl_permission_id' => '41', 'user_acl_role_id' => '15'),
            array('id' => '758', 'user_acl_permission_id' => '42', 'user_acl_role_id' => '15'),
            array('id' => '759', 'user_acl_permission_id' => '43', 'user_acl_role_id' => '15'),
            array('id' => '760', 'user_acl_permission_id' => '68', 'user_acl_role_id' => '15'),
            array('id' => '761', 'user_acl_permission_id' => '69', 'user_acl_role_id' => '15'),
            array('id' => '762', 'user_acl_permission_id' => '70', 'user_acl_role_id' => '15'),
            array('id' => '763', 'user_acl_permission_id' => '73', 'user_acl_role_id' => '15'),
            array('id' => '764', 'user_acl_permission_id' => '44', 'user_acl_role_id' => '15'),
            array('id' => '765', 'user_acl_permission_id' => '45', 'user_acl_role_id' => '15'),
            array('id' => '766', 'user_acl_permission_id' => '46', 'user_acl_role_id' => '15'),
            array('id' => '767', 'user_acl_permission_id' => '47', 'user_acl_role_id' => '15'),
            array('id' => '768', 'user_acl_permission_id' => '48', 'user_acl_role_id' => '15'),
            array('id' => '769', 'user_acl_permission_id' => '49', 'user_acl_role_id' => '15'),
            array('id' => '770', 'user_acl_permission_id' => '50', 'user_acl_role_id' => '15'),
            array('id' => '771', 'user_acl_permission_id' => '51', 'user_acl_role_id' => '15'),
            array('id' => '772', 'user_acl_permission_id' => '52', 'user_acl_role_id' => '15'),
            array('id' => '773', 'user_acl_permission_id' => '53', 'user_acl_role_id' => '15'),
            array('id' => '774', 'user_acl_permission_id' => '54', 'user_acl_role_id' => '15'),
            array('id' => '775', 'user_acl_permission_id' => '58', 'user_acl_role_id' => '15'),
            array('id' => '776', 'user_acl_permission_id' => '56', 'user_acl_role_id' => '15'),
            array('id' => '777', 'user_acl_permission_id' => '57', 'user_acl_role_id' => '15'),
            array('id' => '778', 'user_acl_permission_id' => '71', 'user_acl_role_id' => '15'),
            array('id' => '779', 'user_acl_permission_id' => '72', 'user_acl_role_id' => '15'),
            array('id' => '780', 'user_acl_permission_id' => '59', 'user_acl_role_id' => '15'),
            array('id' => '781', 'user_acl_permission_id' => '60', 'user_acl_role_id' => '15'),
            array('id' => '782', 'user_acl_permission_id' => '61', 'user_acl_role_id' => '15'),
            array('id' => '783', 'user_acl_permission_id' => '62', 'user_acl_role_id' => '15'),
            array('id' => '784', 'user_acl_permission_id' => '63', 'user_acl_role_id' => '15'),
            array('id' => '785', 'user_acl_permission_id' => '64', 'user_acl_role_id' => '15'),
            array('id' => '786', 'user_acl_permission_id' => '65', 'user_acl_role_id' => '15'),
            array('id' => '787', 'user_acl_permission_id' => '66', 'user_acl_role_id' => '15'),
            array('id' => '788', 'user_acl_permission_id' => '67', 'user_acl_role_id' => '15'),
            array('id' => '789', 'user_acl_permission_id' => '74', 'user_acl_role_id' => '15'),
            array('id' => '790', 'user_acl_permission_id' => '75', 'user_acl_role_id' => '15'),
            array('id' => '791', 'user_acl_permission_id' => '76', 'user_acl_role_id' => '15'),
            array('id' => '792', 'user_acl_permission_id' => '77', 'user_acl_role_id' => '15'),
            array('id' => '793', 'user_acl_permission_id' => '81', 'user_acl_role_id' => '15'),
            array('id' => '794', 'user_acl_permission_id' => '82', 'user_acl_role_id' => '15'),
            array('id' => '795', 'user_acl_permission_id' => '83', 'user_acl_role_id' => '15'),
            array('id' => '796', 'user_acl_permission_id' => '84', 'user_acl_role_id' => '15'),
            array('id' => '797', 'user_acl_permission_id' => '87', 'user_acl_role_id' => '15'),
            array('id' => '798', 'user_acl_permission_id' => '88', 'user_acl_role_id' => '15'),
            array('id' => '799', 'user_acl_permission_id' => '89', 'user_acl_role_id' => '15'),
            array('id' => '800', 'user_acl_permission_id' => '90', 'user_acl_role_id' => '15'),
            array('id' => '801', 'user_acl_permission_id' => '91', 'user_acl_role_id' => '15'),
            array('id' => '802', 'user_acl_permission_id' => '92', 'user_acl_role_id' => '15'),
            array('id' => '803', 'user_acl_permission_id' => '93', 'user_acl_role_id' => '15'),
            array('id' => '804', 'user_acl_permission_id' => '80', 'user_acl_role_id' => '15'),
            array('id' => '805', 'user_acl_permission_id' => '78', 'user_acl_role_id' => '15'),
            array('id' => '806', 'user_acl_permission_id' => '79', 'user_acl_role_id' => '15')
        );
        DB::table('user_acl')->truncate();
        DB::table('user_acl')->insert($user_acl);

        $user_acl_permission = array(
            array('id' => '1', 'permission' => 'user/list', 'user_acl_resource_id' => '1'),
            array('id' => '2', 'permission' => 'user/create', 'user_acl_resource_id' => '1'),
            array('id' => '3', 'permission' => 'user/edit', 'user_acl_resource_id' => '1'),
            array('id' => '4', 'permission' => 'user/delete', 'user_acl_resource_id' => '1'),
            array('id' => '5', 'permission' => 'config/system', 'user_acl_resource_id' => '1'),
            array('id' => '6', 'permission' => 'config/general', 'user_acl_resource_id' => '1'),
            array('id' => '7', 'permission' => 'config/server', 'user_acl_resource_id' => '1'),
            array('id' => '8', 'permission' => 'config/update', 'user_acl_resource_id' => '1'),
            array('id' => '9', 'permission' => 'role/list', 'user_acl_resource_id' => '1'),
            array('id' => '10', 'permission' => 'role/create', 'user_acl_resource_id' => '1'),
            array('id' => '11', 'permission' => 'role/edit', 'user_acl_resource_id' => '1'),
            array('id' => '12', 'permission' => 'role/delete', 'user_acl_resource_id' => '1'),
            array('id' => '13', 'permission' => 'media', 'user_acl_resource_id' => '2'),
            array('id' => '35', 'permission' => 'script/delete', 'user_acl_resource_id' => '3'),
            array('id' => '36', 'permission' => 'list', 'user_acl_resource_id' => '4'),
            array('id' => '37', 'permission' => 'install', 'user_acl_resource_id' => '4'),
            array('id' => '38', 'permission' => 'uninstall', 'user_acl_resource_id' => '4'),
            array('id' => '39', 'permission' => 'all', 'user_acl_resource_id' => '5'),
            array('id' => '40', 'permission' => 'Blog', 'user_acl_resource_id' => '4'),
            array('id' => '41', 'permission' => 'feedback/feedbackList', 'user_acl_resource_id' => '1'),
            array('id' => '42', 'permission' => 'feedback/feedbackEdit', 'user_acl_resource_id' => '1'),
            array('id' => '43', 'permission' => 'feedback/feedbackDispute', 'user_acl_resource_id' => '1'),
            array('id' => '44', 'permission' => 'report/list', 'user_acl_resource_id' => '1'),
            array('id' => '45', 'permission' => 'report/newUser', 'user_acl_resource_id' => '1'),
            array('id' => '46', 'permission' => 'report/packageReport', 'user_acl_resource_id' => '1'),
            array('id' => '47', 'permission' => 'report/leaveUser', 'user_acl_resource_id' => '1'),
            array('id' => '48', 'permission' => 'report/lastLoginUsers', 'user_acl_resource_id' => '1'),
            array('id' => '49', 'permission' => 'report/empJobReport', 'user_acl_resource_id' => '1'),
            array('id' => '50', 'permission' => 'report/freJobReport', 'user_acl_resource_id' => '1'),
            array('id' => '51', 'permission' => 'report/pkgIncomeReport', 'user_acl_resource_id' => '1'),
            array('id' => '52', 'permission' => 'report/privateFreelancerReport', 'user_acl_resource_id' => '1'),
            array('id' => '53', 'permission' => 'report/privateStoreReport', 'user_acl_resource_id' => '1'),
            array('id' => '54', 'permission' => 'paymentHistory/list', 'user_acl_resource_id' => '1'),
            array('id' => '55', 'permission' => 'config/editEmail', 'user_acl_resource_id' => '1'),
            array('id' => '56', 'permission' => 'question/list', 'user_acl_resource_id' => '1'),
            array('id' => '57', 'permission' => 'question/create', 'user_acl_resource_id' => '1'),
            array('id' => '58', 'permission' => 'paymentHistory', 'user_acl_resource_id' => '1'),
            array('id' => '59', 'permission' => 'profession/list', 'user_acl_resource_id' => '1'),
            array('id' => '60', 'permission' => 'profession/create', 'user_acl_resource_id' => '1'),
            array('id' => '61', 'permission' => 'profession/edit', 'user_acl_resource_id' => '1'),
            array('id' => '62', 'permission' => 'packageResource/list', 'user_acl_resource_id' => '1'),
            array('id' => '63', 'permission' => 'packageResource/create', 'user_acl_resource_id' => '1'),
            array('id' => '64', 'permission' => 'packageResource/edit', 'user_acl_resource_id' => '1'),
            array('id' => '65', 'permission' => 'package/list', 'user_acl_resource_id' => '1'),
            array('id' => '66', 'permission' => 'package/create', 'user_acl_resource_id' => '1'),
            array('id' => '67', 'permission' => 'package/edit', 'user_acl_resource_id' => '1'),
            array('id' => '68', 'permission' => 'feedback/list', 'user_acl_resource_id' => '1'),
            array('id' => '69', 'permission' => 'feedback/create', 'user_acl_resource_id' => '1'),
            array('id' => '70', 'permission' => 'feedback/edit', 'user_acl_resource_id' => '1'),
            array('id' => '71', 'permission' => 'question/edit', 'user_acl_resource_id' => '1'),
            array('id' => '72', 'permission' => 'question/delete', 'user_acl_resource_id' => '1'),
            array('id' => '73', 'permission' => 'feedback/delete', 'user_acl_resource_id' => '1'),
            array('id' => '74', 'permission' => 'finance/list', 'user_acl_resource_id' => '1'),
            array('id' => '75', 'permission' => 'finance/balancesheet', 'user_acl_resource_id' => '1'),
            array('id' => '76', 'permission' => 'finance/profitloss', 'user_acl_resource_id' => '1'),
            array('id' => '77', 'permission' => 'finance/alltransactions', 'user_acl_resource_id' => '1'),
            array('id' => '81', 'permission' => 'job', 'user_acl_resource_id' => '1'),
            array('id' => '82', 'permission' => 'job/list', 'user_acl_resource_id' => '1'),
            array('id' => '83', 'permission' => 'tax', 'user_acl_resource_id' => '1'),
            array('id' => '84', 'permission' => 'tax/taxList', 'user_acl_resource_id' => '1'),
            array('id' => '87', 'permission' => 'tax/taxEdit', 'user_acl_resource_id' => '1'),
            array('id' => '88', 'permission' => 'tax/taxAdd', 'user_acl_resource_id' => '1'),
            array('id' => '89', 'permission' => 'tax/taxDelete', 'user_acl_resource_id' => '1'),
            array('id' => '90', 'permission' => 'tax/niTaxList', 'user_acl_resource_id' => '1'),
            array('id' => '91', 'permission' => 'tax/niTaxAdd', 'user_acl_resource_id' => '1'),
            array('id' => '92', 'permission' => 'tax/niTaxEdit', 'user_acl_resource_id' => '1'),
            array('id' => '93', 'permission' => 'tax/niTaxDelete', 'user_acl_resource_id' => '1')
        );
        DB::table('user_acl_permission')->truncate();
        DB::table('user_acl_permission')->insert($user_acl_permission);

        $user_acl_resource = array(
            array('id' => '1', 'resource' => 'settings'),
            array('id' => '4', 'resource' => 'modules'),
            array('id' => '5', 'resource' => 'stats')
        );
        DB::table('user_acl_resource')->truncate();
        DB::table('user_acl_resource')->insert($user_acl_resource);

        $view = array(
            array('id' => '1', 'created_at' => '2012-09-19 19:29:04', 'updated_at' => '2019-02-26 09:34:16', 'name' => 'Home page', 'identifier' => 'home', 'description' => 'Home page content'),
            array('id' => '2', 'created_at' => '2012-09-19 19:29:50', 'updated_at' => '2016-07-06 13:55:16', 'name' => 'Blog', 'identifier' => 'blog', 'description' => 'Blog'),
            array('id' => '3', 'created_at' => '2012-09-19 19:32:56', 'updated_at' => '2016-08-03 20:24:01', 'name' => 'Contact', 'identifier' => 'contact', 'description' => 'Contact form'),
            array('id' => '4', 'created_at' => '2012-09-19 19:33:51', 'updated_at' => '2013-05-26 13:26:12', 'name' => 'One column', 'identifier' => 'one-column', 'description' => 'One column page'),
            array('id' => '6', 'created_at' => '2012-10-25 19:57:05', 'updated_at' => '2013-05-26 13:26:12', 'name' => 'Flash messages', 'identifier' => 'flash-messages', 'description' => 'Flash messages displayer'),
            array('id' => '7', 'created_at' => '2013-05-20 15:52:39', 'updated_at' => '2013-05-26 13:26:12', 'name' => 'Paginator', 'identifier' => 'paginator', 'description' => 'Paginator control'),
            array('id' => '8', 'created_at' => '2013-05-22 19:29:57', 'updated_at' => '2013-05-26 13:26:12', 'name' => 'Header', 'identifier' => 'header', 'description' => 'Header'),
            array('id' => '9', 'created_at' => '2013-05-22 19:32:25', 'updated_at' => '2017-05-29 19:47:09', 'name' => 'Footer', 'identifier' => 'footer', 'description' => 'Footer navigation'),
            array('id' => '10', 'created_at' => '2013-05-24 19:02:22', 'updated_at' => '2013-05-26 13:26:12', 'name' => 'Blog categories', 'identifier' => 'blog-categories', 'description' => 'List all categories'),
            array('id' => '11', 'created_at' => '2013-05-24 19:02:59', 'updated_at' => '2016-07-04 21:21:43', 'name' => 'Blog ticket', 'identifier' => 'blog-ticket', 'description' => 'Simple blog ticket'),
            array('id' => '12', 'created_at' => '2016-04-13 21:12:39', 'updated_at' => '2019-02-26 09:14:37', 'name' => 'New Design Header', 'identifier' => 'new-design-header', 'description' => 'New Design Header'),
            array('id' => '13', 'created_at' => '2016-04-13 21:23:38', 'updated_at' => '2019-02-26 09:15:15', 'name' => 'New design footer', 'identifier' => 'new-design-footer', 'description' => 'New Design footer'),
            array('id' => '14', 'created_at' => '2016-04-13 21:45:27', 'updated_at' => '2016-04-13 21:45:27', 'name' => 'test view', 'identifier' => 'test-view', 'description' => 'test view'),
            array('id' => '15', 'created_at' => '2016-04-14 13:26:12', 'updated_at' => '2016-04-14 13:26:27', 'name' => 'logo', 'identifier' => 'site-logo', 'description' => 'site logo'),
            array('id' => '16', 'created_at' => '2016-04-14 18:54:05', 'updated_at' => '2016-04-14 18:54:05', 'name' => 'one column about', 'identifier' => 'one-column-about', 'description' => 'one column about'),
            array('id' => '17', 'created_at' => '2016-04-18 19:16:12', 'updated_at' => '2016-10-17 21:08:58', 'name' => 'Register', 'identifier' => 'register', 'description' => 'register form'),
            array('id' => '18', 'created_at' => '2016-04-19 21:04:25', 'updated_at' => '2016-08-01 19:11:41', 'name' => 'Thank you', 'identifier' => 'thank-you', 'description' => 'thank you view'),
            array('id' => '19', 'created_at' => '2016-04-20 18:21:41', 'updated_at' => '2016-06-18 20:11:55', 'name' => 'Category', 'identifier' => 'category', 'description' => 'category pages'),
            array('id' => '20', 'created_at' => '2016-04-22 17:42:23', 'updated_at' => '2016-07-22 19:12:31', 'name' => 'Package', 'identifier' => 'package', 'description' => 'Package View'),
            array('id' => '21', 'created_at' => '2016-04-22 17:56:50', 'updated_at' => '2016-07-02 17:54:51', 'name' => 'Single Post', 'identifier' => 'single-post', 'description' => 'Single post View'),
            array('id' => '22', 'created_at' => '2016-04-22 18:54:58', 'updated_at' => '2016-04-22 18:54:58', 'name' => 'Ajax process', 'identifier' => 'ajax-request', 'description' => 'ajax request'),
            array('id' => '23', 'created_at' => '2016-04-23 13:19:22', 'updated_at' => '2016-08-03 17:15:32', 'name' => 'User Edit', 'identifier' => 'user-edit', 'description' => 'User Edit'),
            array('id' => '24', 'created_at' => '2016-04-23 13:27:17', 'updated_at' => '2016-08-05 19:41:58', 'name' => 'Login Form', 'identifier' => 'login-form', 'description' => 'Login process'),
            array('id' => '25', 'created_at' => '2016-04-23 13:35:43', 'updated_at' => '2016-08-05 13:00:56', 'name' => 'Forgot password', 'identifier' => 'forgot-password', 'description' => 'forgot password'),
            array('id' => '26', 'created_at' => '2016-04-23 13:45:39', 'updated_at' => '2017-05-29 16:59:50', 'name' => 'User Profile', 'identifier' => 'user-profile', 'description' => 'user profile'),
            array('id' => '27', 'created_at' => '2016-04-23 14:33:34', 'updated_at' => '2016-04-25 18:09:41', 'name' => 'Reset password', 'identifier' => 'reset-password', 'description' => 'Reset Password'),
            array('id' => '28', 'created_at' => '2016-04-23 19:59:30', 'updated_at' => '2016-04-25 21:32:20', 'name' => 'Paypal Process', 'identifier' => 'paypal-process', 'description' => 'Paypal Process'),
            array('id' => '29', 'created_at' => '2016-04-26 21:12:26', 'updated_at' => '2016-04-26 21:12:26', 'name' => 'Report', 'identifier' => 'report', 'description' => 'Report View'),
            array('id' => '30', 'created_at' => '2016-04-28 18:04:45', 'updated_at' => '2016-05-18 20:43:13', 'name' => 'Email Activate', 'identifier' => 'email-activate', 'description' => 'email activate'),
            array('id' => '31', 'created_at' => '2016-05-05 18:54:36', 'updated_at' => '2016-10-18 15:32:55', 'name' => 'Managejob', 'identifier' => 'managejob', 'description' => 'manage job'),
            array('id' => '32', 'created_at' => '2016-05-05 19:22:35', 'updated_at' => '2016-10-18 19:04:43', 'name' => 'Job Search', 'identifier' => 'job-search', 'description' => 'job search'),
            array('id' => '33', 'created_at' => '2016-05-05 19:24:57', 'updated_at' => '2016-10-18 14:19:02', 'name' => 'View Job', 'identifier' => 'view-job', 'description' => 'view job'),
            array('id' => '34', 'created_at' => '2016-05-06 13:07:19', 'updated_at' => '2016-10-19 18:55:25', 'name' => 'Freeze Job', 'identifier' => 'freeze-job', 'description' => 'Job freeze page'),
            array('id' => '35', 'created_at' => '2016-05-06 13:13:00', 'updated_at' => '2016-10-19 18:55:05', 'name' => 'Accept Job', 'identifier' => 'accept-job', 'description' => 'Job acept page'),
            array('id' => '36', 'created_at' => '2016-05-10 21:18:38', 'updated_at' => '2016-05-10 21:18:38', 'name' => 'Build List', 'identifier' => 'build-list', 'description' => 'List of all freelancer who apply for the job'),
            array('id' => '37', 'created_at' => '2016-05-11 17:19:33', 'updated_at' => '2016-07-12 20:26:15', 'name' => 'Build List accept', 'identifier' => 'build-list-accept', 'description' => 'Employer assign job to freelancer'),
            array('id' => '38', 'created_at' => '2016-05-11 20:29:50', 'updated_at' => '2016-10-20 14:20:08', 'name' => 'Single Job', 'identifier' => 'single-job', 'description' => 'Single job view'),
            array('id' => '39', 'created_at' => '2016-05-12 16:05:10', 'updated_at' => '2017-03-16 17:25:15', 'name' => 'Cron Job', 'identifier' => 'cron', 'description' => 'Run various cron activity'),
            array('id' => '40', 'created_at' => '2016-05-12 19:42:23', 'updated_at' => '2017-03-16 17:44:38', 'name' => 'Attendance', 'identifier' => 'attendance', 'description' => 'Check for attendance  if freelance is on job or not'),
            array('id' => '41', 'created_at' => '2016-05-16 18:39:49', 'updated_at' => '2016-10-18 13:48:42', 'name' => 'User Question Edit', 'identifier' => 'user-question-edit', 'description' => 'User question edit'),
            array('id' => '42', 'created_at' => '2016-05-18 17:06:08', 'updated_at' => '2016-05-18 17:06:08', 'name' => 'Feedback', 'identifier' => 'feedback', 'description' => 'Feedback'),
            array('id' => '43', 'created_at' => '2016-05-26 13:10:27', 'updated_at' => '2016-06-22 20:04:19', 'name' => 'Upgrade Package', 'identifier' => 'upgrade-package', 'description' => 'Upgrade Freelance package'),
            array('id' => '44', 'created_at' => '2016-05-26 18:19:47', 'updated_at' => '2016-09-26 14:19:28', 'name' => 'Resend email verification link', 'identifier' => 'resend-email-verify', 'description' => 'Resend email verification link'),
            array('id' => '45', 'created_at' => '2016-06-08 18:37:25', 'updated_at' => '2016-07-12 14:51:16', 'name' => 'Guest Profile', 'identifier' => 'guest-profile', 'description' => 'Partialy register user profile page'),
            array('id' => '46', 'created_at' => '2016-06-10 18:38:20', 'updated_at' => '2017-06-02 20:30:01', 'name' => 'Manage Store', 'identifier' => 'manage-store', 'description' => 'Manage Employer store'),
            array('id' => '47', 'created_at' => '2016-06-16 18:19:49', 'updated_at' => '2016-09-26 21:25:28', 'name' => 'Freelancer Private job', 'identifier' => 'private-job', 'description' => 'Freelancer Private job'),
            array('id' => '48', 'created_at' => '2016-06-18 14:22:12', 'updated_at' => '2016-06-18 14:22:12', 'name' => 'Change Password', 'identifier' => 'change-password', 'description' => 'change password from user profile'),
            array('id' => '49', 'created_at' => '2016-06-20 19:00:16', 'updated_at' => '2016-06-20 19:00:16', 'name' => 'Industry News category', 'identifier' => 'news-categories', 'description' => 'Industry News category'),
            array('id' => '50', 'created_at' => '2016-06-21 17:18:13', 'updated_at' => '2016-06-21 18:39:47', 'name' => 'Manage block freelancer', 'identifier' => 'manage-block-freelancer', 'description' => 'Manage block freelancer user list'),
            array('id' => '51', 'created_at' => '2016-07-31 00:58:56', 'updated_at' => '2016-09-02 20:26:41', 'name' => 'test', 'identifier' => 'test', 'description' => 'test'),
            array('id' => '52', 'created_at' => '2016-12-16 16:42:14', 'updated_at' => '2016-12-16 16:42:14', 'name' => 'Cancel Job', 'identifier' => 'cancel-job', 'description' => 'Cancel job page'),
            array('id' => '53', 'created_at' => '2016-12-29 20:16:00', 'updated_at' => '2016-12-29 20:16:00', 'name' => 'Block User', 'identifier' => 'block-user', 'description' => 'Block User'),
            array('id' => '54', 'created_at' => '2017-01-03 21:09:06', 'updated_at' => '2017-01-03 21:09:06', 'name' => 'How to answer question', 'identifier' => 'how-to-answer-question', 'description' => 'How to answer question'),
            array('id' => '55', 'created_at' => '2017-03-06 13:07:24', 'updated_at' => '2017-03-06 15:14:13', 'name' => 'Details Feedback', 'identifier' => 'feedback-details', 'description' => 'View all feedback'),
            array('id' => '56', 'created_at' => '2017-03-14 20:37:12', 'updated_at' => '2017-03-14 20:37:12', 'name' => 'Expense Cost Form', 'identifier' => 'expense-cost-form', 'description' => 'Expense  Cost read Form'),
            array('id' => '57', 'created_at' => '2017-03-17 18:16:34', 'updated_at' => '2017-03-17 18:16:34', 'name' => 'Feedback Dispute', 'identifier' => 'feedback-dispute', 'description' => 'Feedback Dispute submit'),
            array('id' => '58', 'created_at' => '2017-05-12 17:54:58', 'updated_at' => '2017-05-29 16:35:16', 'name' => 'Finance Detail', 'identifier' => 'finance-detail', 'description' => 'Finance Detail Process'),
            array('id' => '59', 'created_at' => '2017-05-12 18:30:55', 'updated_at' => '2017-05-31 13:40:33', 'name' => 'Add Income', 'identifier' => 'add-income', 'description' => 'Add Income'),
            array('id' => '60', 'created_at' => '2017-05-12 18:47:22', 'updated_at' => '2017-05-23 20:35:26', 'name' => 'Add Expense', 'identifier' => 'add-expense', 'description' => 'Add Expense'),
            array('id' => '61', 'created_at' => '2017-05-12 18:51:48', 'updated_at' => '2017-05-13 21:07:24', 'name' => 'Add Supplier', 'identifier' => 'add-supplier', 'description' => 'Add Supplier'),
            array('id' => '62', 'created_at' => '2017-05-12 18:57:37', 'updated_at' => '2017-05-29 16:57:51', 'name' => 'Cash movement report', 'identifier' => 'cash-movement-report', 'description' => 'Cash movement report'),
            array('id' => '63', 'created_at' => '2017-05-12 19:02:28', 'updated_at' => '2017-05-29 19:12:39', 'name' => 'Open Invoices', 'identifier' => 'open-invoices', 'description' => 'Open Invoices'),
            array('id' => '64', 'created_at' => '2017-05-12 19:24:29', 'updated_at' => '2017-05-29 19:56:45', 'name' => 'Income Filter ', 'identifier' => 'income-filter', 'description' => 'Income Filter '),
            array('id' => '65', 'created_at' => '2017-05-12 19:28:14', 'updated_at' => '2017-05-29 19:42:03', 'name' => 'All Transaction', 'identifier' => 'all-transaction', 'description' => 'All Transaction'),
            array('id' => '66', 'created_at' => '2017-05-12 19:31:10', 'updated_at' => '2017-05-29 16:54:23', 'name' => 'Expenses Type Filter', 'identifier' => 'expenses-type-filter', 'description' => 'Expenses Type Filter'),
            array('id' => '67', 'created_at' => '2017-05-13 20:57:35', 'updated_at' => '2017-05-13 21:09:24', 'name' => 'Supplier list', 'identifier' => 'supplier-list', 'description' => 'supplier-list'),
            array('id' => '68', 'created_at' => '2017-05-16 14:37:50', 'updated_at' => '2017-05-29 16:53:39', 'name' => 'Net Income', 'identifier' => 'net-income', 'description' => 'Net Income'),
            array('id' => '69', 'created_at' => '2017-05-16 14:44:23', 'updated_at' => '2017-05-29 16:53:11', 'name' => 'Net Expense', 'identifier' => 'net-expense', 'description' => 'Net Expense'),
            array('id' => '70', 'created_at' => '2017-05-16 20:28:58', 'updated_at' => '2017-05-29 16:58:26', 'name' => 'Weekly Transaction', 'identifier' => 'weekly-transaction', 'description' => 'Weekly Transaction'),
            array('id' => '71', 'created_at' => '2017-05-16 21:23:15', 'updated_at' => '2017-05-29 19:46:53', 'name' => 'income by area', 'identifier' => 'income-by-area', 'description' => 'income by area'),
            array('id' => '72', 'created_at' => '2017-05-17 13:44:58', 'updated_at' => '2017-05-29 16:56:20', 'name' => 'Weekly Job', 'identifier' => 'weekly-job', 'description' => 'Weekly Job'),
            array('id' => '73', 'created_at' => '2017-05-17 14:31:51', 'updated_at' => '2017-05-29 19:47:48', 'name' => 'income by supplier', 'identifier' => 'income-by-supplier', 'description' => 'income by supplier'),
            array('id' => '74', 'created_at' => '2017-05-18 21:43:40', 'updated_at' => '2017-05-22 20:45:22', 'name' => 'INVOICE PAGE', 'identifier' => 'invoice-page', 'description' => 'INVOICE PAGE'),
            array('id' => '75', 'created_at' => '2017-05-26 22:02:18', 'updated_at' => '2017-05-29 20:03:12', 'name' => 'Employer Finance', 'identifier' => 'employer-finance', 'description' => 'Employer Finance'),
            array('id' => '76', 'created_at' => '2017-05-26 22:04:18', 'updated_at' => '2017-05-26 22:35:10', 'name' => 'Manage Emp Finance', 'identifier' => 'manage-emp-finance', 'description' => 'Manage Emp Finance'),
            array('id' => '77', 'created_at' => '2017-05-29 15:12:40', 'updated_at' => '2017-08-02 15:09:27', 'name' => 'Help', 'identifier' => 'help', 'description' => 'Help'),
            array('id' => '78', 'created_at' => '2017-05-31 20:52:56', 'updated_at' => '2017-08-02 20:51:13', 'name' => 'freelancer report', 'identifier' => 'freelancer-report-page', 'description' => 'freelancer report'),
            array('id' => '79', 'created_at' => '2017-06-06 20:40:58', 'updated_at' => '2017-06-06 20:40:58', 'name' => 'Onday arrival For Sms', 'identifier' => 'onday-arrival', 'description' => 'Onday arrival For Sms'),
            array('id' => '80', 'created_at' => '2017-06-12 15:29:51', 'updated_at' => '2017-06-12 15:29:51', 'name' => 'Show Transactions', 'identifier' => 'show-transactions', 'description' => 'Show Transactions'),
            array('id' => '81', 'created_at' => '2017-06-21 14:30:08', 'updated_at' => '2017-06-21 14:42:31', 'name' => 'Feedback Report', 'identifier' => 'feedback-report', 'description' => 'Feedback Report'),
            array('id' => '83', 'created_at' => '2017-06-29 20:52:30', 'updated_at' => '2017-06-29 20:52:30', 'name' => 'Request Handler View', 'identifier' => 'request-handler-view', 'description' => 'Request Handler View'),
            array('id' => '84', 'created_at' => '2017-07-08 17:39:25', 'updated_at' => '2017-07-08 17:53:17', 'name' => 'Industry news', 'identifier' => 'Industry-news', 'description' => 'Display News'),
            array('id' => '85', 'created_at' => '2017-07-20 19:32:11', 'updated_at' => '2017-07-20 19:36:17', 'name' => 'blog single', 'identifier' => 'blog-single', 'description' => 'blog single'),
            array('id' => '86', 'created_at' => '2017-08-02 19:47:46', 'updated_at' => '2017-08-02 19:47:46', 'name' => 'Finance weekly report', 'identifier' => 'weekly-report', 'description' => 'Weekly report of transaction and job'),
            array('id' => '87', 'created_at' => '2017-10-11 20:07:28', 'updated_at' => '2017-10-11 20:07:28', 'name' => 'Mobo App Web Service', 'identifier' => 'app-web-service', 'description' => 'Mobile app web service layout'),
            array('id' => '88', 'created_at' => '2018-01-27 06:19:14', 'updated_at' => '2018-01-27 06:19:14', 'name' => 'Coming soon', 'identifier' => 'coming-soon', 'description' => 'Coming soon template'),
            array('id' => '89', 'created_at' => '2018-06-12 07:03:19', 'updated_at' => '2018-06-12 09:29:39', 'name' => 'Map view', 'identifier' => 'map-view', 'description' => 'Static uk map page'),
            array('id' => '90', 'created_at' => '2018-11-01 12:46:31', 'updated_at' => '2018-11-01 12:46:31', 'name' => 'Bank Details', 'identifier' => 'bank-details', 'description' => 'To add locum bank details'),
            array('id' => '91', 'created_at' => '2019-02-26 09:17:37', 'updated_at' => '2019-02-26 09:17:37', 'name' => 'Alert pop up', 'identifier' => 'alert-pop-up', 'description' => ''),
            array('id' => '92', 'created_at' => '2019-03-07 07:38:24', 'updated_at' => '2019-03-07 07:38:24', 'name' => 'SEO head template', 'identifier' => 'seo-head', 'description' => 'This is template to place code in head '),
            array('id' => '93', 'created_at' => '2019-03-07 07:41:06', 'updated_at' => '2019-03-07 07:41:31', 'name' => 'SEO body template', 'identifier' => 'seo-body', 'description' => 'This is template to place code in just after body'),
            array('id' => '94', 'created_at' => '2020-04-28 19:54:21', 'updated_at' => '2020-04-28 20:06:00', 'name' => 'Accountancy', 'identifier' => 'accountancy', 'description' => 'Accountancy')
        );
        DB::table('view')->truncate();
        DB::table('view')->insert($view);
    }
}
